#!/usr/bin/env bash
# Deploy all Soroban contracts to testnet in dependency order.
# Outputs contract IDs to contracts/.env.testnet
#
# Usage: ./scripts/deploy-contracts-testnet.sh [--source <identity>] [--fee <stroop>]
#
# Prerequisites:
#   - stellar CLI installed and authenticated (stellar keys list)
#   - STELLAR_ACCOUNT env var set, or pass --source <identity>
#   - Network: testnet (https://soroban-testnet.stellar.org)
#
# Deploy order (respects contract dependencies):
#   access-control → stellar_insights → analytics → governance →
#   escrow → token-swap → multi-sig-wallet → time-locked-transactions → upgrade

set -euo pipefail

# ── Configuration ─────────────────────────────────────────────────────────────

CONTRACTS_DIR="$(cd "$(dirname "$0")/../contracts" && pwd)"
ENV_FILE="${CONTRACTS_DIR}/.env.testnet"
NETWORK="testnet"
RPC_URL="https://soroban-testnet.stellar.org"
NETWORK_PASSPHRASE="Test SDF Network ; September 2015"
FEE="${STELLAR_FEE:-100}"

# ── Parse arguments ────────────────────────────────────────────────────────────

SOURCE="${STELLAR_ACCOUNT:-}"

while [[ $# -gt 0 ]]; do
    case $1 in
        --source) SOURCE="$2"; shift 2 ;;
        --fee)    FEE="$2";    shift 2 ;;
        *) echo "Unknown argument: $1"; exit 1 ;;
    esac
done

if [[ -z "${SOURCE}" ]]; then
    echo "Error: deployer identity not set."
    echo "  Set STELLAR_ACCOUNT env var or pass --source <identity>"
    exit 1
fi

# ── Helpers ────────────────────────────────────────────────────────────────────

log()  { echo "[$(date -u +%H:%M:%S)] $*"; }
info() { echo "  $*"; }

deploy_contract() {
    local name="$1"   # human-readable label
    local wasm="$2"   # path to .wasm file
    local alias="$3"  # env-file key (e.g. ACCESS_CONTROL_CONTRACT_ID)

    log "Deploying ${name}..."
    if [[ ! -f "${wasm}" ]]; then
        echo "  Error: wasm not found at ${wasm}"
        echo "  Run 'cd contracts && cargo build --release --target wasm32v1-none' first."
        exit 1
    fi

    local contract_id
    contract_id=$(stellar contract deploy \
        --wasm "${wasm}" \
        --source "${SOURCE}" \
        --network "${NETWORK}" \
        --fee "${FEE}" \
        2>&1 | grep -E '^[A-Z0-9]{56}$' | tail -1)

    if [[ -z "${contract_id}" ]]; then
        echo "  Error: failed to deploy ${name} — no contract ID returned."
        exit 1
    fi

    info "${alias}=${contract_id}"
    echo "${alias}=${contract_id}" >> "${ENV_FILE}"
    echo "${contract_id}"
}

# ── Build ──────────────────────────────────────────────────────────────────────

log "Building all contracts for release..."
(cd "${CONTRACTS_DIR}" && cargo build --release --target wasm32v1-none 2>&1 | tail -5)
log "Build complete."

# ── Deploy ─────────────────────────────────────────────────────────────────────

WASM_DIR="${CONTRACTS_DIR}/target/wasm32v1-none/release"

# Start fresh env file
cat > "${ENV_FILE}" <<EOF
# Testnet contract IDs — generated by deploy-contracts-testnet.sh
# Network:    ${NETWORK}
# RPC URL:    ${RPC_URL}
# Passphrase: ${NETWORK_PASSPHRASE}
# Deployer:   ${SOURCE}

EOF

log "Starting deployment to ${NETWORK}..."
echo ""

# 1. access-control — no dependencies
ACCESS_CONTROL_ID=$(deploy_contract \
    "access-control" \
    "${WASM_DIR}/access_control.wasm" \
    "ACCESS_CONTROL_CONTRACT_ID")

# 2. stellar_insights — depends on access-control
STELLAR_INSIGHTS_ID=$(deploy_contract \
    "stellar_insights" \
    "${WASM_DIR}/stellar_insights.wasm" \
    "STELLAR_INSIGHTS_CONTRACT_ID")

# 3. analytics — depends on stellar_insights
ANALYTICS_ID=$(deploy_contract \
    "analytics" \
    "${WASM_DIR}/analytics.wasm" \
    "ANALYTICS_CONTRACT_ID")

# 4. governance — depends on analytics
GOVERNANCE_ID=$(deploy_contract \
    "governance" \
    "${WASM_DIR}/governance.wasm" \
    "GOVERNANCE_CONTRACT_ID")

# 5. escrow — depends on stellar_insights
ESCROW_ID=$(deploy_contract \
    "escrow" \
    "${WASM_DIR}/escrow.wasm" \
    "ESCROW_CONTRACT_ID")

# 6. token-swap — depends on stellar_insights
TOKEN_SWAP_ID=$(deploy_contract \
    "token-swap" \
    "${WASM_DIR}/token_swap.wasm" \
    "TOKEN_SWAP_CONTRACT_ID")

# 7. multi-sig-wallet — depends on access-control
MULTI_SIG_ID=$(deploy_contract \
    "multi-sig-wallet" \
    "${WASM_DIR}/multi_sig_wallet.wasm" \
    "MULTI_SIG_WALLET_CONTRACT_ID")

# 8. time-locked-transactions — depends on access-control
TIME_LOCKED_ID=$(deploy_contract \
    "time-locked-transactions" \
    "${WASM_DIR}/time_locked_transactions.wasm" \
    "TIME_LOCKED_TRANSACTIONS_CONTRACT_ID")

# 9. upgrade — depends on governance
UPGRADE_ID=$(deploy_contract \
    "upgrade" \
    "${WASM_DIR}/upgrade.wasm" \
    "UPGRADE_CONTRACT_ID")

# ── Summary ────────────────────────────────────────────────────────────────────

echo ""
log "All contracts deployed successfully."
log "Contract IDs written to: ${ENV_FILE}"
echo ""
echo "  ACCESS_CONTROL_CONTRACT_ID=${ACCESS_CONTROL_ID}"
echo "  STELLAR_INSIGHTS_CONTRACT_ID=${STELLAR_INSIGHTS_ID}"
echo "  ANALYTICS_CONTRACT_ID=${ANALYTICS_ID}"
echo "  GOVERNANCE_CONTRACT_ID=${GOVERNANCE_ID}"
echo "  ESCROW_CONTRACT_ID=${ESCROW_ID}"
echo "  TOKEN_SWAP_CONTRACT_ID=${TOKEN_SWAP_ID}"
echo "  MULTI_SIG_WALLET_CONTRACT_ID=${MULTI_SIG_ID}"
echo "  TIME_LOCKED_TRANSACTIONS_CONTRACT_ID=${TIME_LOCKED_ID}"
echo "  UPGRADE_CONTRACT_ID=${UPGRADE_ID}"
echo ""
log "Source the env file with: source ${ENV_FILE}"
